### ISSUE TITLE
Cannot build with Qt version < 4.4

### ISSUE THREAD

**Issue by rudilee** [flavio/qjson#73]
I can't compile qjson with Qt 4.2.1, there is no QT_BEGIN_NAMESPACE and QT_END_NAMESPACE macros and no QRunnable interface which is according to Qt's doc introduced in Qt 4.4, perhaps the Qt version requirement in the README need to be corrected to "Qt 4.4 or greater"?

**Comment by flavio** [comment]
fixed with 7fd4b564017aa2e9611efd242a735fe317f67842

**Comment by rudilee** [comment]
I'm sorry, i kinda overlook the failure messages when compiling with Qt 4.2.1, looking further to the failures messages, there's complain about no QVariantHash in Qt 4.2.1, according to Qt's doc it's introduced in Qt 4.5.
